// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.addAccessTokenStmt, err = db.PrepareContext(ctx, addAccessToken); err != nil {
		return nil, fmt.Errorf("error preparing query AddAccessToken: %w", err)
	}
	if q.addAppUserStmt, err = db.PrepareContext(ctx, addAppUser); err != nil {
		return nil, fmt.Errorf("error preparing query AddAppUser: %w", err)
	}
	if q.addClientStmt, err = db.PrepareContext(ctx, addClient); err != nil {
		return nil, fmt.Errorf("error preparing query AddClient: %w", err)
	}
	if q.addEntryStmt, err = db.PrepareContext(ctx, addEntry); err != nil {
		return nil, fmt.Errorf("error preparing query AddEntry: %w", err)
	}
	if q.addIdentityUserStmt, err = db.PrepareContext(ctx, addIdentityUser); err != nil {
		return nil, fmt.Errorf("error preparing query AddIdentityUser: %w", err)
	}
	if q.addRefreshTokenStmt, err = db.PrepareContext(ctx, addRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query AddRefreshToken: %w", err)
	}
	if q.assignUserRoleStmt, err = db.PrepareContext(ctx, assignUserRole); err != nil {
		return nil, fmt.Errorf("error preparing query AssignUserRole: %w", err)
	}
	if q.deleteAccessTokenByIDStmt, err = db.PrepareContext(ctx, deleteAccessTokenByID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAccessTokenByID: %w", err)
	}
	if q.deleteClientByIDStmt, err = db.PrepareContext(ctx, deleteClientByID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteClientByID: %w", err)
	}
	if q.deleteIdentityUserByIDStmt, err = db.PrepareContext(ctx, deleteIdentityUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteIdentityUserByID: %w", err)
	}
	if q.deleteRefreshTokenByIDStmt, err = db.PrepareContext(ctx, deleteRefreshTokenByID); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteRefreshTokenByID: %w", err)
	}
	if q.getAccessTokenByJWTStmt, err = db.PrepareContext(ctx, getAccessTokenByJWT); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccessTokenByJWT: %w", err)
	}
	if q.getBoostrapConditionsStmt, err = db.PrepareContext(ctx, getBoostrapConditions); err != nil {
		return nil, fmt.Errorf("error preparing query GetBoostrapConditions: %w", err)
	}
	if q.getClientByIDStmt, err = db.PrepareContext(ctx, getClientByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetClientByID: %w", err)
	}
	if q.getEntryByIDStmt, err = db.PrepareContext(ctx, getEntryByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetEntryByID: %w", err)
	}
	if q.getEntryBySHA1Stmt, err = db.PrepareContext(ctx, getEntryBySHA1); err != nil {
		return nil, fmt.Errorf("error preparing query GetEntryBySHA1: %w", err)
	}
	if q.getEntryOwnerIDStmt, err = db.PrepareContext(ctx, getEntryOwnerID); err != nil {
		return nil, fmt.Errorf("error preparing query GetEntryOwnerID: %w", err)
	}
	if q.getIdentityUserByUsernameStmt, err = db.PrepareContext(ctx, getIdentityUserByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query GetIdentityUserByUsername: %w", err)
	}
	if q.getRefreshTokenByJWTStmt, err = db.PrepareContext(ctx, getRefreshTokenByJWT); err != nil {
		return nil, fmt.Errorf("error preparing query GetRefreshTokenByJWT: %w", err)
	}
	if q.getUserMaxScopeStmt, err = db.PrepareContext(ctx, getUserMaxScope); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserMaxScope: %w", err)
	}
	if q.markBootstrapConditionSatisfiedStmt, err = db.PrepareContext(ctx, markBootstrapConditionSatisfied); err != nil {
		return nil, fmt.Errorf("error preparing query MarkBootstrapConditionSatisfied: %w", err)
	}
	if q.revokeAccessTokenByIDStmt, err = db.PrepareContext(ctx, revokeAccessTokenByID); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeAccessTokenByID: %w", err)
	}
	if q.revokeRefreshTokenByIDStmt, err = db.PrepareContext(ctx, revokeRefreshTokenByID); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeRefreshTokenByID: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.addAccessTokenStmt != nil {
		if cerr := q.addAccessTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addAccessTokenStmt: %w", cerr)
		}
	}
	if q.addAppUserStmt != nil {
		if cerr := q.addAppUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addAppUserStmt: %w", cerr)
		}
	}
	if q.addClientStmt != nil {
		if cerr := q.addClientStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addClientStmt: %w", cerr)
		}
	}
	if q.addEntryStmt != nil {
		if cerr := q.addEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addEntryStmt: %w", cerr)
		}
	}
	if q.addIdentityUserStmt != nil {
		if cerr := q.addIdentityUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addIdentityUserStmt: %w", cerr)
		}
	}
	if q.addRefreshTokenStmt != nil {
		if cerr := q.addRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing addRefreshTokenStmt: %w", cerr)
		}
	}
	if q.assignUserRoleStmt != nil {
		if cerr := q.assignUserRoleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing assignUserRoleStmt: %w", cerr)
		}
	}
	if q.deleteAccessTokenByIDStmt != nil {
		if cerr := q.deleteAccessTokenByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAccessTokenByIDStmt: %w", cerr)
		}
	}
	if q.deleteClientByIDStmt != nil {
		if cerr := q.deleteClientByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteClientByIDStmt: %w", cerr)
		}
	}
	if q.deleteIdentityUserByIDStmt != nil {
		if cerr := q.deleteIdentityUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteIdentityUserByIDStmt: %w", cerr)
		}
	}
	if q.deleteRefreshTokenByIDStmt != nil {
		if cerr := q.deleteRefreshTokenByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteRefreshTokenByIDStmt: %w", cerr)
		}
	}
	if q.getAccessTokenByJWTStmt != nil {
		if cerr := q.getAccessTokenByJWTStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccessTokenByJWTStmt: %w", cerr)
		}
	}
	if q.getBoostrapConditionsStmt != nil {
		if cerr := q.getBoostrapConditionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBoostrapConditionsStmt: %w", cerr)
		}
	}
	if q.getClientByIDStmt != nil {
		if cerr := q.getClientByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getClientByIDStmt: %w", cerr)
		}
	}
	if q.getEntryByIDStmt != nil {
		if cerr := q.getEntryByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEntryByIDStmt: %w", cerr)
		}
	}
	if q.getEntryBySHA1Stmt != nil {
		if cerr := q.getEntryBySHA1Stmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEntryBySHA1Stmt: %w", cerr)
		}
	}
	if q.getEntryOwnerIDStmt != nil {
		if cerr := q.getEntryOwnerIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getEntryOwnerIDStmt: %w", cerr)
		}
	}
	if q.getIdentityUserByUsernameStmt != nil {
		if cerr := q.getIdentityUserByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getIdentityUserByUsernameStmt: %w", cerr)
		}
	}
	if q.getRefreshTokenByJWTStmt != nil {
		if cerr := q.getRefreshTokenByJWTStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRefreshTokenByJWTStmt: %w", cerr)
		}
	}
	if q.getUserMaxScopeStmt != nil {
		if cerr := q.getUserMaxScopeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserMaxScopeStmt: %w", cerr)
		}
	}
	if q.markBootstrapConditionSatisfiedStmt != nil {
		if cerr := q.markBootstrapConditionSatisfiedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing markBootstrapConditionSatisfiedStmt: %w", cerr)
		}
	}
	if q.revokeAccessTokenByIDStmt != nil {
		if cerr := q.revokeAccessTokenByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeAccessTokenByIDStmt: %w", cerr)
		}
	}
	if q.revokeRefreshTokenByIDStmt != nil {
		if cerr := q.revokeRefreshTokenByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeRefreshTokenByIDStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                  DBTX
	tx                                  *sql.Tx
	addAccessTokenStmt                  *sql.Stmt
	addAppUserStmt                      *sql.Stmt
	addClientStmt                       *sql.Stmt
	addEntryStmt                        *sql.Stmt
	addIdentityUserStmt                 *sql.Stmt
	addRefreshTokenStmt                 *sql.Stmt
	assignUserRoleStmt                  *sql.Stmt
	deleteAccessTokenByIDStmt           *sql.Stmt
	deleteClientByIDStmt                *sql.Stmt
	deleteIdentityUserByIDStmt          *sql.Stmt
	deleteRefreshTokenByIDStmt          *sql.Stmt
	getAccessTokenByJWTStmt             *sql.Stmt
	getBoostrapConditionsStmt           *sql.Stmt
	getClientByIDStmt                   *sql.Stmt
	getEntryByIDStmt                    *sql.Stmt
	getEntryBySHA1Stmt                  *sql.Stmt
	getEntryOwnerIDStmt                 *sql.Stmt
	getIdentityUserByUsernameStmt       *sql.Stmt
	getRefreshTokenByJWTStmt            *sql.Stmt
	getUserMaxScopeStmt                 *sql.Stmt
	markBootstrapConditionSatisfiedStmt *sql.Stmt
	revokeAccessTokenByIDStmt           *sql.Stmt
	revokeRefreshTokenByIDStmt          *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                  tx,
		tx:                                  tx,
		addAccessTokenStmt:                  q.addAccessTokenStmt,
		addAppUserStmt:                      q.addAppUserStmt,
		addClientStmt:                       q.addClientStmt,
		addEntryStmt:                        q.addEntryStmt,
		addIdentityUserStmt:                 q.addIdentityUserStmt,
		addRefreshTokenStmt:                 q.addRefreshTokenStmt,
		assignUserRoleStmt:                  q.assignUserRoleStmt,
		deleteAccessTokenByIDStmt:           q.deleteAccessTokenByIDStmt,
		deleteClientByIDStmt:                q.deleteClientByIDStmt,
		deleteIdentityUserByIDStmt:          q.deleteIdentityUserByIDStmt,
		deleteRefreshTokenByIDStmt:          q.deleteRefreshTokenByIDStmt,
		getAccessTokenByJWTStmt:             q.getAccessTokenByJWTStmt,
		getBoostrapConditionsStmt:           q.getBoostrapConditionsStmt,
		getClientByIDStmt:                   q.getClientByIDStmt,
		getEntryByIDStmt:                    q.getEntryByIDStmt,
		getEntryBySHA1Stmt:                  q.getEntryBySHA1Stmt,
		getEntryOwnerIDStmt:                 q.getEntryOwnerIDStmt,
		getIdentityUserByUsernameStmt:       q.getIdentityUserByUsernameStmt,
		getRefreshTokenByJWTStmt:            q.getRefreshTokenByJWTStmt,
		getUserMaxScopeStmt:                 q.getUserMaxScopeStmt,
		markBootstrapConditionSatisfiedStmt: q.markBootstrapConditionSatisfiedStmt,
		revokeAccessTokenByIDStmt:           q.revokeAccessTokenByIDStmt,
		revokeRefreshTokenByIDStmt:          q.revokeRefreshTokenByIDStmt,
	}
}
