// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type AppBootstrap struct {
	ConditionName string
	Satisfied     int64
}

type AppUser struct {
	UserID   string
	IsAdmin  int64
	Username string
}

type IdpClient struct {
	ClientID     string
	ClientSecret string
}

type IdpRefreshToken struct {
	TokenID  string
	ClientID string
	Jwt      string
	Revoked  int64
}

type IdpUser struct {
	UserID       string
	Username     string
	Email        string
	PasswordHash []byte
}
