// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	AddAccessToken(ctx context.Context, arg AddAccessTokenParams) (*AddAccessTokenRow, error)
	AddAppUser(ctx context.Context, arg AddAppUserParams) (*AppUser, error)
	AddClient(ctx context.Context, arg AddClientParams) (*IdpClient, error)
	AddEntry(ctx context.Context, arg AddEntryParams) (*AddEntryRow, error)
	AddIdentityUser(ctx context.Context, arg AddIdentityUserParams) (*IdpUser, error)
	AddRefreshToken(ctx context.Context, arg AddRefreshTokenParams) (*IdpRefreshToken, error)
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	DeleteAccessTokenByID(ctx context.Context, tokenID string) error
	DeleteClientByID(ctx context.Context, clientID string) error
	DeleteIdentityUserByID(ctx context.Context, userID string) error
	DeleteRefreshTokenByID(ctx context.Context, tokenID string) error
	GetAccessTokenByJWT(ctx context.Context, jwt string) (*GetAccessTokenByJWTRow, error)
	GetBoostrapConditions(ctx context.Context) ([]*AppBootstrap, error)
	GetClientByID(ctx context.Context, clientID string) (*IdpClient, error)
	GetEntryByID(ctx context.Context, entryID int64) (*GetEntryByIDRow, error)
	GetEntryBySHA1(ctx context.Context, arg GetEntryBySHA1Params) (*GetEntryBySHA1Row, error)
	GetEntryOwnerID(ctx context.Context, entryID int64) (string, error)
	GetIdentityUserByUsername(ctx context.Context, username string) (*IdpUser, error)
	GetRefreshTokenByJWT(ctx context.Context, jwt string) (*IdpRefreshToken, error)
	// Returns the highest scope level for a user's permission on a resource type and operation.
	// COALESCE returns 0 if MAX is NULL (when user has no roles or no matching permissions).
	// Scope levels: 0 = none/no permission, 1 = none, 2 = own, 3 = global
	GetUserMaxScope(ctx context.Context, arg GetUserMaxScopeParams) (interface{}, error)
	MarkBootstrapConditionSatisfied(ctx context.Context, conditionName string) (*AppBootstrap, error)
	RevokeAccessTokenByID(ctx context.Context, tokenID string) (*RevokeAccessTokenByIDRow, error)
	RevokeRefreshTokenByID(ctx context.Context, tokenID string) (*IdpRefreshToken, error)
}

var _ Querier = (*Queries)(nil)
