// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	GetBoostrapConditions(ctx context.Context) ([]*WallabagoBootstrap, error)
	MarkBootstrapConditionSatisfied(ctx context.Context, conditionName string) (*WallabagoBootstrap, error)
}

var _ Querier = (*Queries)(nil)
