CREATE TABLE wallabago.entries (
	entry_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	owner_id TEXT NOT NULL REFERENCES wallabago.users (user_id),
	title TEXT NOT NULL,
	url TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	retrieved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	content TEXT NOT NULL,
	sha1 BYTEA NOT NULL
)
;