// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type IdentityClient struct {
	ClientID     string
	ClientSecret string
}

type IdentityRefreshToken struct {
	TokenID  string
	ClientID string
	Jwt      string
	Revoked  bool
}

type IdentityUser struct {
	UserID       string
	Username     string
	Email        string
	PasswordHash []byte
}
