// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	AddAccessToken(ctx context.Context, arg AddAccessTokenParams) (*AddAccessTokenRow, error)
	AddClient(ctx context.Context, arg AddClientParams) (*IdentityClient, error)
	AddRefreshToken(ctx context.Context, arg AddRefreshTokenParams) (*IdentityRefreshToken, error)
	AddUser(ctx context.Context, arg AddUserParams) (*IdentityUser, error)
	DeleteAccessTokenByID(ctx context.Context, tokenID string) error
	DeleteClientByID(ctx context.Context, clientID string) error
	DeleteRefreshTokenByID(ctx context.Context, tokenID string) error
	DeleteUserByID(ctx context.Context, userID string) error
	GetAccessTokenByJWT(ctx context.Context, jwt string) (*GetAccessTokenByJWTRow, error)
	GetClientByID(ctx context.Context, clientID string) (*IdentityClient, error)
	GetRefreshTokenByJWT(ctx context.Context, jwt string) (*IdentityRefreshToken, error)
	GetUserByUsername(ctx context.Context, username string) (*IdentityUser, error)
	RevokeAccessTokenByID(ctx context.Context, tokenID string) (*RevokeAccessTokenByIDRow, error)
	RevokeRefreshTokenByID(ctx context.Context, tokenID string) (*IdentityRefreshToken, error)
}

var _ Querier = (*Queries)(nil)
