x-commons:
  env:
    - &otel-traces-env
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4317
    - &otel-metrics-env
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://otel-collector:4317
    - &otel-logs-env
      OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: http://otel-collector:4317

services:
  wallabago:
    networks:
      - wallabago
    build: ../../
    restart: no
    environment:
      <<:
        # Uncomment for OTEL:
        # - *otel-traces-env
        # - *otel-metrics-env
        # - *otel-logs-env
      WALLABAGO_PORT: 7080
    ports:
      - 7080:7080
    develop:
      watch:
        - path: ../../internal/
          action: rebuild
        - path: ../../cmd/
          action: rebuild

networks:
  wallabago:
