x-commons:
  env: 
    - &otel-traces-env
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4317
    - &otel-metrics-env
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://otel-collector:4317
    - &otel-logs-env
      OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: http://otel-collector:4317
    - &db-env
      DB: "postgresql://wallabago-api:wallabago@postgres:5432/wallabago-db?sslmode=disable&application_name=wallabago-api-client"

services:
  identity-migrations:
    networks:
      - wallabago-signoz
      - wallabago
    image: migrate/migrate:v4.18.3
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../../internal/identity/database/migrations/:/migrations
    environment:
      <<:
        - *otel-traces-env
        - *otel-metrics-env
        - *otel-logs-env 
        - *db-env
    entrypoint: ["/bin/sh", "-c", "migrate -path=/migrations/ -database \"$$DB&x-migrations-table=identity_migrations\" up"]

  migrations:
    networks:
      - wallabago-signoz
      - wallabago
    image: migrate/migrate:v4.18.3
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../../internal/database/migrations/:/migrations
    environment:
      <<:
        - *otel-traces-env
        - *otel-metrics-env
        - *otel-logs-env 
        - *db-env
    entrypoint: ["/bin/sh", "-c", "migrate -path=/migrations/ -database $$DB up"]

  wallabago:
    networks:
      - wallabago-signoz
      - wallabago
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      identity-migrations:
        condition: service_completed_successfully

    build: ../../
    restart: no
    environment:
      <<:
        - *otel-traces-env
        - *otel-metrics-env
        - *otel-logs-env 
        - *db-env
    ports:
      - 7080:8080

  postgres:
    networks:
      - wallabago
    image: postgres:17
    ports:
      - 25432:5432
    environment:
      POSTGRES_USER: wallabago-api
      POSTGRES_PASSWORD: wallabago
      POSTGRES_DB: wallabago-db
    healthcheck:
      # we use CMD-SHELL with sh in order to allow string interpolation
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"]
      start_interval: 1s
      start_period: 5s
      timeout: 5s
      interval: 10s
      retries: 10
        
networks:
  wallabago:
  wallabago-signoz:
    name: wallabago-signoz
    external: true
